Create idempotency-is-not-enough.md
exactly-once/Home pull request #2
Opened 2019-08-09 12:00 UTC by tmasternak

2019-08-09 12:52 UTC, SzymonPobiega commented on content/docs/idempotency-is-not-enough.md
> +Idempotency can be a useful property when building distributed systems. It's easier said than done however to write idempotent code and keep it so under changing requirements. Finally, generic idempo
```suggestion
Idempotency can be a useful property when building distributed systems. It's easier said than done, however, to write idempotent code and keep it so under changing requirements. Finally, generic idempotency is not enough to deal with basic characteristics of communication in distributed systems.
```

2019-08-09 12:52 UTC, SzymonPobiega commented on content/docs/idempotency-is-not-enough.md
> +There are couple definitions of idempotency but the one we will use here states that:
```suggestion
There are a couple of definitions of idempotency but the one we will use here states that: 
```

2019-08-09 12:54 UTC, SzymonPobiega commented on content/docs/idempotency-is-not-enough.md
> +In order to get some intuition let's figure out what `f` and `x` stand for in practice. To cover different flavours of practical architectures let's assume that our system consists of number of endpo
```suggestion
In order to get some intuition let's figure out what `f` and `x` stand for in practice. To cover different flavours of practical architectures let's assume that our system consists of a number of endpoints. Each endpoint owns a distinct piece of state and the only way for the endpoints to communicate is by sending messages. Every endpoint processes input messages one by one, modifying it's internal state and producing new messages (1).
```

2019-08-09 12:55 UTC, SzymonPobiega commented on content/docs/idempotency-is-not-enough.md
> +It's worth going through a trivial example to see what does idempotency means in a more concrete settings. Let's imagine that our system models a moving target shooting range. It consists of a single
```suggestion
It's worth going through a trivial example to see what does idempotency mean in a more concrete settings. Let's imagine that our system models a moving target shooting range. It consists of a single `ShootingRange` endpoint which stores shooting target's location `{int: ShootingTarget}` and processes `FireAt : { int: Target }` messages. Whenever `FireAt` message gets processed the endpoint produces either `Hit` or `Missed` event to indicate the result.
```

2019-08-09 12:57 UTC, SzymonPobiega commented on content/docs/idempotency-is-not-enough.md
> +What this shows is an instance of a broader scenario. Whenever the logic depends on values outside of our control that can change between exectusion the operation is no longer idempotent. This includ
```suggestion
What this shows is an instance of a broader scenario. Whenever the logic depends on values outside of our control that can change between executions, the operation is no longer idempotent. This includes not only random numbers, but things like GUIDs, local clock values, results of queries to the local file system or remote APIs. If you depend on time or GUID identifiers you need to make then deterministic (1). 
```

2019-08-09 12:59 UTC, SzymonPobiega commented on content/docs/idempotency-is-not-enough.md
> +What we need is ability to recognize duplicates at the business level and to be able to that we need some business level identify for each one of them. In other words we need logical message identifi
```suggestion
What we need is ability to recognize duplicates at the business level and, to be able to that, we need some business level identity for each one of them. In other words we need logical message identifiers to be able to cope with duplicates at the logic level. 
```

2019-08-09 13:00 UTC, SzymonPobiega commented on content/docs/idempotency-is-not-enough.md
> +What this trivial scenario shows is that generic idempotency is not enough to deal with message duplicates. We need business level identifiers to deal with duplicated messages.
Hmmm what if the business domain does not have a concept of `AttemptId`?

2019-08-12 19:23 UTC, tmasternak commented
I've reordered the content. I need one more sitting to make it final and ping you for review.

2019-08-19 17:58 UTC, tmasternak commented
@SzymonPobiega can you have another look. I've re-arranged the content a bit.

2019-08-20 04:59 UTC, SzymonPobiega requested changes
Added some minor edits

2019-08-20 04:59 UTC, SzymonPobiega commented on content/docs/idempotency-is-not-enough.md
> +This covers a pretty wide range of systems. Most notably service-based architectures build on top of modern messaging infrastructure - both on-prem and in the cloud [^1].
```suggestion
This covers a pretty wide range of systems. Most notably service-based architectures build on top of modern messaging infrastructure - both on-premise and in the cloud [^1]. 
```

2019-08-20 04:59 UTC, SzymonPobiega commented on content/docs/idempotency-is-not-enough.md
> +With at-least-once delivery, any in-flight message gets delivered possibly multiple times. This is a direct consequence of communication protocols used as any message will be re-deliver until it gets
```suggestion
With at-least-once delivery, any in-flight message gets delivered possibly multiple times. This is a direct consequence of communication protocols used as any message will be re-delivered until it gets acknowledged by the receiver. Duplicates are also created on the producer side as the producer needs to retry sending messages until it gets an acknowledgement from the infrastructure. 
```

2019-08-20 04:59 UTC, SzymonPobiega commented on content/docs/idempotency-is-not-enough.md
> +Duplication and re-ordering happen both at the same which makes any duplication and re-ordering of in-flight messages possible.
```suggestion
When combined, duplication and re-ordering can produce, at the receiver side, any sequence of messages. The only guarantee is that the resulting sequence contains at least one copy of each message sent. 
```

2019-08-27 07:37 UTC, SzymonPobiega approved these changes

2019-09-04 07:23 UTC, merged